version: 2

sources:
  - name: landing_zone
    schema: landing_zone
    description: >
      Camada de ingestão contendo dados brutos provenientes da API Alpha Vantage.
      Os dados podem conter inconsistências de tipo, formatação e valores faltantes.
      A chave lógica da tabela é composta pela combinação de (symbol, date).
    
    tables:
      - name: csv_symbol_countries
        description: >
            Tabela estática com os países de origem dos ativos analisados.
        columns:
          - name: symbol
            description: "Ticker do ativo conforme retornado pela API"
          - name: country
            description: "País do ativo analisado"
      # --------------------------- #
      - name: alphavantage_stock_prices_daily
        description: >
            Tabela com cotações diárias de ativos financeiros em formato bruto,
            sem tratamento ou validação de qualidade.
        columns:
          - name: symbol
            description: "Ticker do ativo conforme retornado pela API"

          - name: date
            description: "Data da cotação em formato string (YYYY-MM-DD)"

          - name: open
            description: "Preço de abertura (string na origem)"

          - name: high
            description: "Maior preço do dia (string na origem)"

          - name: low
            description: "Menor preço do dia (string na origem)"

          - name: close
            description: "Preço de fechamento (string na origem)"

          - name: volume
            description: "Volume negociado (string na origem)"